baseURL = 'https://biblicaldhiman.github.io/'
languageCode = 'en-us'
title = 'Rajat Dhiman'
theme = "PaperMod"

DefaultContentLanguage = "en"

copyright = "© Rajat Dhiman"
defaultContentLanguage = "en"
disableKinds = ["taxonomy"]
enableRobotsTXT = true
timeZone = "Asia/Kolkata"
timeout = "120s"

[params]
  theme = "dark"
  darkmode = true
  description = "Follower of Jesus Christ in India"
  title = "Rajat Dhiman"
  socialIcons = [
    { icon = "twitter", url = "https://x.com/biblical_dhiman"},
    { icon = "facebook", url = "https://www.facebook.com/dhiman.biblical"},
    { icon = "instagram", url = "https://www.instagram.com/irajatism" },
    { icon = "youtube", url = "mailto:rddhiman10@gmail.com" },
    { icon = "email", url = "mailto:yourname@example.com" },
    { icon = "spotify", url = "https://open.spotify.com/show/2Ov2HrUlLcQWERnJifyJhs" }
  ]

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML"]
  section = ["HTML"]

[imaging]
  quality = 75
  resampleFilter = "CatmullRom"
  [imaging.exif]
    disableDate = false
    disableLatLong = true
    includeFields = "ImageDescription|Orientation"

[menu] 
  [[menu.main]] 
    name = "About"
    weight = 100 
    identifier = "About"
    url = "/about" 
  [[menu.main]] 
    name = "Podcasts"
    identifier = "Podcasts"
    weight = 300
    url = "/podcasts"
  [[menu.main]]
    name = "Contact" 
    identifier = "Contact" 
    weight = 400
    url = "/contact"

[services]
  [services.rss]
    limit = 100

[params.hero]
  image = "https://assets.about.me/background/users/b/i/b/biblical_dhiman_1671217535_663.jpg"
  alt = "Rajat Dhiman's profile picture"
  position = "center"